networks:
  dev: #choose name you want instead of network1

name: your_project_name

services:
  app:
    image: nginx:stable-alpine
    container_name: ${PROJECT_NAME}-app
    volumes:
      - "./etc/app/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/app/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./etc/ssl:/etc/ssl"
      - "./log/app/:/var/log/app/"
      - "../web/app/:/var/www/html/app/"
      - "./log/ui/:/var/log/ui/"
      - "../web/ui/:/var/www/html/ui/"
    ports:
      - "8088:80"
      - "3000:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: on-failure
    depends_on:
      - php-fpm
      - mysqldb

  php-fpm:
    build:
      context: dockerfiles/php
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-php-fpm
    volumes:
      - "../web/app:/var/www/html/app"

  node:
    command: tail -f /etc/hosts
    container_name: ${PROJECT_NAME}-node
    build:
      context: dockerfiles/node
      dockerfile: Dockerfile
    restart: no
    volumes:
      - "../web/ui:/var/www/html/ui"
    working_dir: "/var/www/html/ui/"

  composer:
    build:
      context: dockerfiles/composer
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-composer
    volumes:
      - "../web/app:/var/www/html/app"

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: on-failure
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}-${MYSQL_HOST}
    restart: on-failure
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
